## POLITISKY 2024 - Community Detection (NLP Tool)

In [2]:
import polars as pl
from pathlib import Path

data_path = Path("D:/Thesis/aria2-1.37.0-win-64bit-build1")

user_post_history_df = pl.scan_parquet(
    data_path / "user_post_history_dataset.parquet"
)

# Check the schema
user_post_history_df.collect_schema()

# View the first 5 rows
user_post_history_df.head(5).collect()

shape: (5, 16)
┌──────────┬────────┬─────────────┬─────────────┬───┬────────────┬─────────┬──────────┬────────────┐
│ PostId   ┆ UserId ┆ PostTime    ┆ Content     ┆ … ┆ QuoteConte ┆ IsReply ┆ ParentId ┆ ParentUser │
│ ---      ┆ ---    ┆ ---         ┆ ---         ┆   ┆ nt         ┆ ---     ┆ ---      ┆ Id         │
│ i64      ┆ i64    ┆ str         ┆ str         ┆   ┆ ---        ┆ bool    ┆ i64      ┆ ---        │
│          ┆        ┆             ┆             ┆   ┆ str        ┆         ┆          ┆ i64        │
╞══════════╪════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪══════════╪════════════╡
│ 7840946  ┆ 167406 ┆ 2024-11-19T ┆ it’s a      ┆ … ┆            ┆ true    ┆ 15792425 ┆ 345622     │
│          ┆        ┆ 23:12:12.09 ┆ tragedy of  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 2Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ commons.…   ┆   ┆            ┆         ┆          ┆            │
│ 17079336 ┆ 377198 ┆ 2024-11-19T ┆ Notícia da  ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11Z   ┆ @anonymous  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ "Xi Jin…    ┆   ┆            ┆         ┆          ┆            │
│ 9179962  ┆ 196837 ┆ 2024-11-19T ┆ Have you    ┆ … ┆            ┆ true    ┆ 15458353 ┆ 336741     │
│          ┆        ┆ 23:12:11.29 ┆ run it by   ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 8Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Godless…    ┆   ┆            ┆         ┆          ┆            │
│ 2108430  ┆ 45089  ┆ 2024-11-19T ┆ This! This  ┆ … ┆ WATCH:     ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11.08 ┆ is the      ┆   ┆ “You’re a  ┆         ┆          ┆            │
│          ┆        ┆ 4Z          ┆ energy we   ┆   ┆ baby       ┆         ┆          ┆            │
│          ┆        ┆             ┆ ne…         ┆   ┆ shit.”     ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆ …          ┆         ┆          ┆            │
│ 4231604  ┆ 90172  ┆ 2024-11-19T ┆ WATCH:      ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:10Z   ┆ Trending    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Stories:    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Gas P…      ┆   ┆            ┆         ┆          ┆            │
└──────────┴────────┴─────────────┴─────────────┴───┴────────────┴─────────┴──────────┴────────────┘

In [3]:
user_post_history_df.collect_schema()

Schema([('PostId', Int64),
        ('UserId', Int64),
        ('PostTime', String),
        ('Content', String),
        ('Hashtags', List(String)),
        ('Languages', List(String)),
        ('Mentions', List(Int64)),
        ('IsRepost', Boolean),
        ('SourceUserId', Int64),
        ('IsQuote', Boolean),
        ('QuoteId', Int64),
        ('QuoteUserId', Int64),
        ('QuoteContent', String),
        ('IsReply', Boolean),
        ('ParentId', Int64),
        ('ParentUserId', Int64)])

In [4]:
user_post_history_df.head(5).collect()

shape: (5, 16)
┌──────────┬────────┬─────────────┬─────────────┬───┬────────────┬─────────┬──────────┬────────────┐
│ PostId   ┆ UserId ┆ PostTime    ┆ Content     ┆ … ┆ QuoteConte ┆ IsReply ┆ ParentId ┆ ParentUser │
│ ---      ┆ ---    ┆ ---         ┆ ---         ┆   ┆ nt         ┆ ---     ┆ ---      ┆ Id         │
│ i64      ┆ i64    ┆ str         ┆ str         ┆   ┆ ---        ┆ bool    ┆ i64      ┆ ---        │
│          ┆        ┆             ┆             ┆   ┆ str        ┆         ┆          ┆ i64        │
╞══════════╪════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪══════════╪════════════╡
│ 7840946  ┆ 167406 ┆ 2024-11-19T ┆ it’s a      ┆ … ┆            ┆ true    ┆ 15792425 ┆ 345622     │
│          ┆        ┆ 23:12:12.09 ┆ tragedy of  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 2Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ commons.…   ┆   ┆            ┆         ┆          ┆            │
│ 17079336 ┆ 377198 ┆ 2024-11-19T ┆ Notícia da  ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11Z   ┆ @anonymous  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ "Xi Jin…    ┆   ┆            ┆         ┆          ┆            │
│ 9179962  ┆ 196837 ┆ 2024-11-19T ┆ Have you    ┆ … ┆            ┆ true    ┆ 15458353 ┆ 336741     │
│          ┆        ┆ 23:12:11.29 ┆ run it by   ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 8Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Godless…    ┆   ┆            ┆         ┆          ┆            │
│ 2108430  ┆ 45089  ┆ 2024-11-19T ┆ This! This  ┆ … ┆ WATCH:     ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11.08 ┆ is the      ┆   ┆ “You’re a  ┆         ┆          ┆            │
│          ┆        ┆ 4Z          ┆ energy we   ┆   ┆ baby       ┆         ┆          ┆            │
│          ┆        ┆             ┆ ne…         ┆   ┆ shit.”     ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆ …          ┆         ┆          ┆            │
│ 4231604  ┆ 90172  ┆ 2024-11-19T ┆ WATCH:      ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:10Z   ┆ Trending    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Stories:    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Gas P…      ┆   ┆            ┆         ┆          ┆            │
└──────────┴────────┴─────────────┴─────────────┴───┴────────────┴─────────┴──────────┴────────────┘

In [5]:
user_post_history_df.select(pl.len()).collect().item()

18416787

In [6]:
rows = user_post_history_df.select(pl.len()).collect().item()
cols = len(user_post_history_df.collect_schema().names())

print("Rows:", rows)
print("Columns:", cols)

Rows: 18416787
Columns: 16

In [7]:
user_post_history_df.select(
    pl.all().null_count()
).collect()

shape: (1, 16)
┌────────┬────────┬──────────┬─────────┬───┬──────────────┬─────────┬──────────┬──────────────┐
│ PostId ┆ UserId ┆ PostTime ┆ Content ┆ … ┆ QuoteContent ┆ IsReply ┆ ParentId ┆ ParentUserId │
│ ---    ┆ ---    ┆ ---      ┆ ---     ┆   ┆ ---          ┆ ---     ┆ ---      ┆ ---          │
│ u32    ┆ u32    ┆ u32      ┆ u32     ┆   ┆ u32          ┆ u32     ┆ u32      ┆ u32          │
╞════════╪════════╪══════════╪═════════╪═══╪══════════════╪═════════╪══════════╪══════════════╡
│ 0      ┆ 0      ┆ 0        ┆ 0       ┆ … ┆ 0            ┆ 0       ┆ 0        ┆ 0            │
└────────┴────────┴──────────┴─────────┴───┴──────────────┴─────────┴──────────┴──────────────┘

Check column names.

In [8]:
user_post_history_df.collect_schema().names()

['PostId',
 'UserId',
 'PostTime',
 'Content',
 'Hashtags',
 'Languages',
 'Mentions',
 'IsRepost',
 'SourceUserId',
 'IsQuote',
 'QuoteId',
 'QuoteUserId',
 'QuoteContent',
 'IsReply',
 'ParentId',
 'ParentUserId']

In [2]:
print(user_post_history_df.collect_schema())

Schema({'PostId': Int64, 'UserId': Int64, 'PostTime': String, 'Content': String, 'Hashtags': List(String), 'Languages': List(String), 'Mentions': List(Int64), 'IsRepost': Boolean, 'SourceUserId': Int64, 'IsQuote': Boolean, 'QuoteId': Int64, 'QuoteUserId': Int64, 'QuoteContent': String, 'IsReply': Boolean, 'ParentId': Int64, 'ParentUserId': Int64})

In [3]:
print(
    user_post_history_df
    .select(pl.len())
    .collect(engine="streaming")
)

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 18416787 │
└──────────┘

In [4]:
text_stats = (
    user_post_history_df
    .select(
        pl.col("Content").str.len_chars().max().alias("max_length"),
        pl.col("Content").str.len_chars().mean().alias("avg_length")
    )
    .collect(engine="streaming")
)

print(text_stats)

shape: (1, 2)
┌────────────┬────────────┐
│ max_length ┆ avg_length │
│ ---        ┆ ---        │
│ u32        ┆ f64        │
╞════════════╪════════════╡
│ 1176       ┆ 124.540174 │
└────────────┴────────────┘

In [ ]:
posts_df = (user_post_history_df.select("Content").filter(pl.col("Content").is_not_null()).collect(engine="streaming"))

print(posts_df.shape)

(18416787, 1)

In [8]:
documents = posts_df["Content"].to_list()

print("Posts:", len(documents))

Posts: 18416787

In [ ]:
documents = (posts_df["Content"].drop_nulls().to_list())

print("Total posts:", len(documents))
print("Sample post:", documents[0])

Total posts: 18416787
Sample post: it’s a tragedy of the commons. so. anyone and everyone that ‘flies’ is a fracker. no matter how selectively they choose which science stuff to “believe” or not “believe”. if you fly you are a fracker.

In [4]:
from sentence_transformers import SentenceTransformer

c:\Users\geryl\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1390.03it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\geryl\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\geryl\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [15]:
documents = (posts_df["Content"].drop_nulls().head(10000).to_list())

print("Number of posts:", len(documents))
print("Sample post:", documents[0])

Number of posts: 10000
Sample post: it’s a tragedy of the commons. so. anyone and everyone that ‘flies’ is a fracker. no matter how selectively they choose which science stuff to “believe” or not “believe”. if you fly you are a fracker.

In [16]:
embeddings = embedding_model.encode(
    documents,
    batch_size=16,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embedding shape:", embeddings.shape)

Batches: 100%|██████████| 625/625 [03:13<00:00,  3.23it/s]

Embedding shape: (10000, 384)

In [17]:
from bertopic import BERTopic

topic_model = BERTopic(
    embedding_model=None,
    min_topic_size=20,
    verbose=True
)

topics, probabilities = topic_model.fit_transform(
    documents,
    embeddings
)

2026-10-31 13:30:22,241 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-10-31 13:32:02,990 - BERTopic - Dimensionality - Completed ✓
2026-10-31 13:32:02,998 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-10-31 13:32:04,318 - BERTopic - Cluster - Completed ✓
2026-10-31 13:32:04,345 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-10-31 13:32:04,972 - BERTopic - Representation - Completed ✓

In [18]:
topic_info = topic_model.get_topic_info()

topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3279,-1_the_to_it_of,"[the, to, it, of, is, and, we, you, with, in]",[@anonymous curious question lets just say you...
1,0,586,0_thank_yes_thanks_you,"[thank, yes, thanks, you, oh, welcome, yep, lo...","[Thank you!🤗, Thank you!🤗, Thank you!!]"
2,1,302,1_oz_medicare_dr_medicaid,"[oz, medicare, dr, medicaid, doctor, tv, mehme...",[Dr. Oz Pushes Medicare Privatization—the infa...
3,2,188,2_ukraine_russian_putin_russia,"[ukraine, russian, putin, russia, nuclear, war...","[Oh wow, so you’re telling me the piece of pap..."
4,3,108,3_farmers_tax_prices_kgm,"[farmers, tax, prices, kgm, tariffs, brexit, c...",[NEW: I wrote about how companies like John De...
...,...,...,...,...,...
126,125,23,125_jd_vance_seen_thinks,"[jd, vance, seen, thinks, wheres, imbeciles, m...","[Has anyone seen JD Vance?, Has anyone seen JD..."
127,126,22,126_hogan_hulk_chairing_chiefs,"[hogan, hulk, chairing, chiefs, joint, staff, ...","[What’s next, Hulk Hogan chairing the Joint Ch..."
128,127,22,127_sense_does_doesnt_make,"[sense, does, doesnt, make, it, unity, somethi...","[It doesn't make sense does it?, It doesn't ma..."
129,128,21,128_treason_traitor_traitors_hamhocks,"[treason, traitor, traitors, hamhocks, insuffe...",[If Americans keep electing rapist traitors ca...
130,129,21,129_anonymous_here_found_see,"[anonymous, here, found, see, you, nice, glad,...","[@anonymous Nice to see you here!, @anonymous ..."

In [19]:
topic_info = topic_model.get_topic_info()

topic_info.select(["Topic", "Name", "Count"])

     Topic                                   Name  Count
0       -1                        -1_the_to_it_of   3279
1        0                 0_thank_yes_thanks_you    586
2        1              1_oz_medicare_dr_medicaid    302
3        2         2_ukraine_russian_putin_russia    188
4        3               3_farmers_tax_prices_kgm    108
..     ...                                    ...    ...
126    125               125_jd_vance_seen_thinks     23
127    126         126_hogan_hulk_chairing_chiefs     22
128    127             127_sense_does_doesnt_make     22
129    128  128_treason_traitor_traitors_hamhocks     21
130    129           129_anonymous_here_found_see     21

[131 rows x 3 columns]