## POLITISKY 2024 - Community Detection (NLP Tool)

In [1]:
import polars as pl
from pathlib import Path

data_path = Path("D:/Thesis/aria2-1.37.0-win-64bit-build1")

user_post_history_df = pl.scan_parquet(
    data_path / "user_post_history_dataset.parquet"
)

# Check the schema
user_post_history_df.collect_schema()

# View the first 5 rows
user_post_history_df.head(5).collect()

shape: (5, 16)
┌──────────┬────────┬─────────────┬─────────────┬───┬────────────┬─────────┬──────────┬────────────┐
│ PostId   ┆ UserId ┆ PostTime    ┆ Content     ┆ … ┆ QuoteConte ┆ IsReply ┆ ParentId ┆ ParentUser │
│ ---      ┆ ---    ┆ ---         ┆ ---         ┆   ┆ nt         ┆ ---     ┆ ---      ┆ Id         │
│ i64      ┆ i64    ┆ str         ┆ str         ┆   ┆ ---        ┆ bool    ┆ i64      ┆ ---        │
│          ┆        ┆             ┆             ┆   ┆ str        ┆         ┆          ┆ i64        │
╞══════════╪════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪══════════╪════════════╡
│ 7840946  ┆ 167406 ┆ 2024-11-19T ┆ it’s a      ┆ … ┆            ┆ true    ┆ 15792425 ┆ 345622     │
│          ┆        ┆ 23:12:12.09 ┆ tragedy of  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 2Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ commons.…   ┆   ┆            ┆         ┆          ┆            │
│ 17079336 ┆ 377198 ┆ 2024-11-19T ┆ Notícia da  ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11Z   ┆ @anonymous  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ "Xi Jin…    ┆   ┆            ┆         ┆          ┆            │
│ 9179962  ┆ 196837 ┆ 2024-11-19T ┆ Have you    ┆ … ┆            ┆ true    ┆ 15458353 ┆ 336741     │
│          ┆        ┆ 23:12:11.29 ┆ run it by   ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 8Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Godless…    ┆   ┆            ┆         ┆          ┆            │
│ 2108430  ┆ 45089  ┆ 2024-11-19T ┆ This! This  ┆ … ┆ WATCH:     ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11.08 ┆ is the      ┆   ┆ “You’re a  ┆         ┆          ┆            │
│          ┆        ┆ 4Z          ┆ energy we   ┆   ┆ baby       ┆         ┆          ┆            │
│          ┆        ┆             ┆ ne…         ┆   ┆ shit.”     ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆ …          ┆         ┆          ┆            │
│ 4231604  ┆ 90172  ┆ 2024-11-19T ┆ WATCH:      ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:10Z   ┆ Trending    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Stories:    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Gas P…      ┆   ┆            ┆         ┆          ┆            │
└──────────┴────────┴─────────────┴─────────────┴───┴────────────┴─────────┴──────────┴────────────┘

In [2]:
user_post_history_df.collect_schema()

Schema([('PostId', Int64),
        ('UserId', Int64),
        ('PostTime', String),
        ('Content', String),
        ('Hashtags', List(String)),
        ('Languages', List(String)),
        ('Mentions', List(Int64)),
        ('IsRepost', Boolean),
        ('SourceUserId', Int64),
        ('IsQuote', Boolean),
        ('QuoteId', Int64),
        ('QuoteUserId', Int64),
        ('QuoteContent', String),
        ('IsReply', Boolean),
        ('ParentId', Int64),
        ('ParentUserId', Int64)])

In [3]:
user_post_history_df.head(5).collect()

shape: (5, 16)
┌──────────┬────────┬─────────────┬─────────────┬───┬────────────┬─────────┬──────────┬────────────┐
│ PostId   ┆ UserId ┆ PostTime    ┆ Content     ┆ … ┆ QuoteConte ┆ IsReply ┆ ParentId ┆ ParentUser │
│ ---      ┆ ---    ┆ ---         ┆ ---         ┆   ┆ nt         ┆ ---     ┆ ---      ┆ Id         │
│ i64      ┆ i64    ┆ str         ┆ str         ┆   ┆ ---        ┆ bool    ┆ i64      ┆ ---        │
│          ┆        ┆             ┆             ┆   ┆ str        ┆         ┆          ┆ i64        │
╞══════════╪════════╪═════════════╪═════════════╪═══╪════════════╪═════════╪══════════╪════════════╡
│ 7840946  ┆ 167406 ┆ 2024-11-19T ┆ it’s a      ┆ … ┆            ┆ true    ┆ 15792425 ┆ 345622     │
│          ┆        ┆ 23:12:12.09 ┆ tragedy of  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 2Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ commons.…   ┆   ┆            ┆         ┆          ┆            │
│ 17079336 ┆ 377198 ┆ 2024-11-19T ┆ Notícia da  ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11Z   ┆ @anonymous  ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ "Xi Jin…    ┆   ┆            ┆         ┆          ┆            │
│ 9179962  ┆ 196837 ┆ 2024-11-19T ┆ Have you    ┆ … ┆            ┆ true    ┆ 15458353 ┆ 336741     │
│          ┆        ┆ 23:12:11.29 ┆ run it by   ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆ 8Z          ┆ the         ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Godless…    ┆   ┆            ┆         ┆          ┆            │
│ 2108430  ┆ 45089  ┆ 2024-11-19T ┆ This! This  ┆ … ┆ WATCH:     ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:11.08 ┆ is the      ┆   ┆ “You’re a  ┆         ┆          ┆            │
│          ┆        ┆ 4Z          ┆ energy we   ┆   ┆ baby       ┆         ┆          ┆            │
│          ┆        ┆             ┆ ne…         ┆   ┆ shit.”     ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆             ┆   ┆ …          ┆         ┆          ┆            │
│ 4231604  ┆ 90172  ┆ 2024-11-19T ┆ WATCH:      ┆ … ┆            ┆ false   ┆ -1       ┆ -1         │
│          ┆        ┆ 23:12:10Z   ┆ Trending    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Stories:    ┆   ┆            ┆         ┆          ┆            │
│          ┆        ┆             ┆ Gas P…      ┆   ┆            ┆         ┆          ┆            │
└──────────┴────────┴─────────────┴─────────────┴───┴────────────┴─────────┴──────────┴────────────┘

In [4]:
user_post_history_df.select(pl.len()).collect().item()

18416787

In [5]:
rows = user_post_history_df.select(pl.len()).collect().item()
cols = len(user_post_history_df.collect_schema().names())

print("Rows:", rows)
print("Columns:", cols)

Rows: 18416787
Columns: 16

In [6]:
user_post_history_df.select(pl.all().null_count()).collect()

shape: (1, 16)
┌────────┬────────┬──────────┬─────────┬───┬──────────────┬─────────┬──────────┬──────────────┐
│ PostId ┆ UserId ┆ PostTime ┆ Content ┆ … ┆ QuoteContent ┆ IsReply ┆ ParentId ┆ ParentUserId │
│ ---    ┆ ---    ┆ ---      ┆ ---     ┆   ┆ ---          ┆ ---     ┆ ---      ┆ ---          │
│ u32    ┆ u32    ┆ u32      ┆ u32     ┆   ┆ u32          ┆ u32     ┆ u32      ┆ u32          │
╞════════╪════════╪══════════╪═════════╪═══╪══════════════╪═════════╪══════════╪══════════════╡
│ 0      ┆ 0      ┆ 0        ┆ 0       ┆ … ┆ 0            ┆ 0       ┆ 0        ┆ 0            │
└────────┴────────┴──────────┴─────────┴───┴──────────────┴─────────┴──────────┴──────────────┘

Check column names.

In [7]:
user_post_history_df.collect_schema().names()

['PostId',
 'UserId',
 'PostTime',
 'Content',
 'Hashtags',
 'Languages',
 'Mentions',
 'IsRepost',
 'SourceUserId',
 'IsQuote',
 'QuoteId',
 'QuoteUserId',
 'QuoteContent',
 'IsReply',
 'ParentId',
 'ParentUserId']

In [8]:
print(
    user_post_history_df
    .select(pl.len())
    .collect(engine="streaming")
)

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 18416787 │
└──────────┘

In [9]:
text_stats = (
    user_post_history_df
    .select(
        pl.col("Content").str.len_chars().max().alias("max_length"),
        pl.col("Content").str.len_chars().mean().alias("avg_length")
    )
    .collect(engine="streaming")
)

print(text_stats)

shape: (1, 2)
┌────────────┬────────────┐
│ max_length ┆ avg_length │
│ ---        ┆ ---        │
│ u32        ┆ f64        │
╞════════════╪════════════╡
│ 1176       ┆ 124.540174 │
└────────────┴────────────┘

In [10]:
posts_df = (user_post_history_df.select("Content").filter(pl.col("Content").is_not_null()).collect(engine="streaming"))

print(posts_df.shape)

(18416787, 1)

In [11]:
documents = posts_df["Content"].to_list()

print("Posts:", len(documents))

Posts: 18416787

In [13]:
documents = (posts_df["Content"].drop_nulls().to_list())

print("Total posts:", len(documents))
print("Sample post:", documents[0])

Total posts: 18416787
Sample post: it’s a tragedy of the commons. so. anyone and everyone that ‘flies’ is a fracker. no matter how selectively they choose which science stuff to “believe” or not “believe”. if you fly you are a fracker.

In [14]:
from sentence_transformers import SentenceTransformer

c:\Users\geryl\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2167.04it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [16]:
documents = (posts_df["Content"].drop_nulls().head(5000).to_list())

print("Number of posts:", len(documents))
print("Sample post:", documents[0])

Number of posts: 5000
Sample post: it’s a tragedy of the commons. so. anyone and everyone that ‘flies’ is a fracker. no matter how selectively they choose which science stuff to “believe” or not “believe”. if you fly you are a fracker.

# Data Cleaning (Removing of Stop/Filler Words)

In [32]:
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

custom_stop_words = list(
    ENGLISH_STOP_WORDS.union({
        "like", "just", "really", "actually",
        "thing", "things", "yeah", "okay",
        "know", "think", "going", "said", "to", "the", 
        "and", "but", "or", "if", "so", "httpsanonymous", 
        "you", "i", "it", "this", "that", "we", "he", 
        "she", "they", "for", "with", "on", "at", "by", 
        "from", "as", "an", "be", "are", "was", "were",
        "have", "has", "had", "do", "does", "did",
        "not", "no", "yes", "all", "any", "some",
        "on", "ty", "dont"
    })
)

def clean_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Remove custom stop words
    pattern = r"\b(" + "|".join(
        re.escape(word) for word in custom_stop_words
    ) + r")\b"

    text = re.sub(pattern, " ", text)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text)

    return text.strip()

cleaned_documents = [
    clean_text(doc) for doc in documents
]

In [33]:
embeddings = embedding_model.encode(
    cleaned_documents,
    show_progress_bar=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches: 100%|██████████| 157/157 [00:47<00:00,  3.34it/s]

Embedding shape: (5000, 384)

In [43]:
from bertopic import BERTopic

topic_model = BERTopic(
    embedding_model=None,
    min_topic_size=20,
    verbose=True
)

topics, probabilities = topic_model.fit_transform(
    cleaned_documents,
    embeddings
)

2026-10-31 14:54:42,370 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-10-31 14:54:44,862 - BERTopic - Dimensionality - Completed ✓
2026-10-31 14:54:44,867 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-10-31 14:54:45,092 - BERTopic - Cluster - Completed ✓
2026-10-31 14:54:45,092 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-10-31 14:54:45,211 - BERTopic - Representation - Completed ✓

In [44]:
topic_info = topic_model.get_topic_info()

topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1777,-1_anonymous_people_dont_make,"[anonymous, people, dont, make, trump, nice, v...","[keeps saying blue sky reminds old twitter, “ ..."
1,0,511,0_thank_hope_lol_thanks,"[thank, hope, lol, thanks, oh, good, god, welc...","[thank !, ! thank ! 💙, thank !]"
2,1,194,1_dr_oz_medicare_medicaid,"[dr, oz, medicare, medicaid, doctor, doctors, ...",[donald trump nominated dr oz lead cms. doctor...
3,2,127,2_ukraine_russian_putin_russia,"[ukraine, russian, putin, russia, budapest, uk...","[commemoration 1,000th day russia's brutal, un..."
4,3,124,3_education_secretary_mcmahon_linda,"[education, secretary, mcmahon, linda, wwe, de...",[trump transition -chair linda mcmahon expecte...
5,4,118,4_read_english_sound_dread,"[read, english, sound, dread, abilities, archi...","[read 👇, read 👇, people idiots don’t understan..."
6,5,106,5_restaurant_petty_little_plucked,"[restaurant, petty, little, plucked, milk, app...",[«cuisiner québécois» s’avère payant pour une ...
7,6,104,6_democrats_dems_election_vote,"[democrats, dems, election, vote, votes, voter...",[ah.. ’s “rigged” 🙄 want legitimate votes coun...
8,7,98,7_joe_mika_msnbc_media,"[joe, mika, msnbc, media, news, scarborough, m...",[morning joe mika brzezinski disgrace entire p...
9,8,97,8_block_blocked_list_maga,"[block, blocked, list, maga, accounts, bait, m...",[reminder: don’t rage bait. magats swarming bl...
10,9,94,9_elon_musk_spacex_rocket,"[elon, musk, spacex, rocket, trump, donald, bo...",[months donald trump bragging elon musk spacex...
11,10,92,10_thread_entry_awaitingtreasurypick_pilot,"[thread, entry, awaitingtreasurypick, pilot, o...","[#thread baaa acro entry, #thread baaa acro en..."
12,11,87,11_da_que_la_sem,"[da, que, la, sem, notcia, paywall, los, se, e...","[notícia da @anonymous ""pf: general com plano ..."
13,12,78,12_trans_biological_bathroom_female,"[trans, biological, bathroom, female, women, u...","[, women don’t use urinals use private stalls ..."
14,13,65,13_country_dictator_genocide_democracy,"[country, dictator, genocide, democracy, gaza,...","[treason committed country, leader, hamhocks, ..."
15,14,64,14_book_books_read_timothy,"[book, books, read, timothy, snyder, bible, re...",[favorite chapters “ tyranny” timothy snyder c...
16,15,55,15_covid_pandemic_5g_rfk,"[covid, pandemic, 5g, rfk, health, jr, public,...","[2021, rfk jr. claimed covid quarantine used r..."
17,16,54,16_sex_accused_traffickers_sexual,"[sex, accused, traffickers, sexual, agencies, ...","[’s trump administration loves, ’s naming cred..."
18,17,50,17_japan_reuters_jp_gigazine,"[japan, reuters, jp, gigazine, nhk, coindesk, ...",[プーチン氏、核ドクトリン改定承認 米国のウクライナ支援に警告 - ロイター (reuter...
19,18,50,18_follow_anonymous_ambitious_storytelling,"[follow, anonymous, ambitious, storytelling, s...","[@anonymous follow ., @anonymous follow ., @an..."
20,19,49,19_ballsacktv_music_streaming_ballsackradio,"[ballsacktv, music, streaming, ballsackradio, ...",[panchiko - portraits mv: shunsaku hayashi str...
21,20,48,20_game_studio_art_veryyyy,"[game, studio, art, veryyyy, template, knight,...",[’m veryyyy excited announce video game publis...
22,21,48,21_victory_strength_writing_remember,"[victory, strength, writing, remember, suffer,...","[""survival isn’t strong; ’s clinging pieces ha..."
23,22,48,22____,"[, , , , , , , , , ]","[, , ]"
24,23,47,23____,"[, , , , , , , , , ]","[, , ]"
25,24,46,24____,"[, , , , , , , , , ]","[, , ]"
26,25,45,25_maga_dems_sociodemographic_partly,"[maga, dems, sociodemographic, partly, plays, ...","[maga means want make american ""great"" ... 's ..."
27,26,45,26_anonymous_hahahahahahahahahahahah_convos_qu...,"[anonymous, hahahahahahahahahahahah, convos, q...","[@anonymous @anonymous, 👏 @anonymous, @anonymous]"
28,27,43,27____,"[, , , , , , , , , ]","[, , ]"
29,28,41,28_twitter_followers_twitterx_circling,"[twitter, followers, twitterx, circling, drain...","[twitter., 's twitter?, twitter.]"
30,29,41,29_climate_emissions_carbon_fuel,"[climate, emissions, carbon, fuel, conservativ...",[actively advocating increase extraction burni...
31,30,38,30_appointees_policy_doj_positions,"[appointees, policy, doj, positions, tells, no...",[trump choosing b-list celebs showboats lead g...
32,31,37,31_anonymous_bluesky_bluecrew_nodemunder1k,"[anonymous, bluesky, bluecrew, nodemunder1k, r...",[#bluecrew #resist #nodemunder1k true blues! f...
33,32,37,32____,"[, , , , , , , , , ]","[, , ]"
34,33,35,33_gaetz_matt_ethics_ag,"[gaetz, matt, ethics, ag, objections, reconsid...",[senate republicans' objections gaetz ag ethic...
35,34,34,34____,"[, , , , , , , , , ]","[, , ]"
36,35,33,35_threads_bluesky_journalists_twitter,"[threads, bluesky, journalists, twitter, musk,...",[threads massive goal. open hostility journali...
37,36,33,36_cabinet_term_picks_federal,"[cabinet, term, picks, federal, root, leaking,...","["" root unprecedented approach... abiding dist..."
38,37,33,37____,"[, , , , , , , , , ]","[, , ]"
39,38,29,38_food_housing_costs_deporting,"[food, housing, costs, deporting, worried, low...",[love hear republican worried food housing cos...
40,39,29,39_fascism_operation_normandy_defeated,"[fascism, operation, normandy, defeated, waves...",[operation overlord (1944) largest allied oper...
41,40,27,40_posts_followed_reposted_follow,"[posts, followed, reposted, follow, likes, pos...","[followed reposted., followed reposted., follo..."
42,41,26,41_buy_oh_let_sure,"[buy, oh, let, sure, , , , , , ]","[let ., oh ..., buy ..]"
43,42,25,42_anonymous_democracypromoters_better_soverei...,"[anonymous, democracypromoters, better, sovere...",[better ! #democracypromoters 🌊💙🗽☮️ @anonymous...
44,43,25,43____,"[, , , , , , , , , ]","[, , ]"
45,44,24,44_mace_nancy_survivor_delaware,"[mace, nancy, survivor, delaware, donors, adju...",[’ witnessing crass cruelty nancy mace. chases...
46,45,23,45_white_black_racism_philosophers,"[white, black, racism, philosophers, greenpeac...",['m old cajun ike & white signs staff trainer ...
47,46,23,46_judges_court_supreme_kavanaugh,"[judges, court, supreme, kavanaugh, 6elon, hea...",[look controversies lies dump appointed kavana...
48,47,22,47_states_state_red_orange,"[states, state, red, orange, blue, invade, usn...",[trump wants use red state troops invade blue ...
49,48,21,48_usa_freedom_knuckle_salivating,"[usa, freedom, knuckle, salivating, draggers, ...",[usa ‘ greatest nation’ earth. lie fed dumb pe...

In [45]:
import json

topic_info = topic_model.get_topic_info()

all_topics = []

for _, row in topic_info.iterrows():

    topic_id = int(row["Topic"])

    # Get keywords and scores
    keywords = topic_model.get_topic(topic_id)

    # Get representative posts
    representative_docs = topic_model.get_representative_docs(topic_id)

    all_topics.append({
        "topic_id": topic_id,
        "topic_title": str(row["Name"]),
        "post_count": int(row["Count"]),
        "keywords": [
            {
                "word": word,
                "score": float(score)
            }
            for word, score in (keywords or [])
        ],
        "representative_posts": representative_docs or []
    })

# Save JSON
output_path = data_path / "bertopic_generated_topics.json"

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(all_topics, f, ensure_ascii=False, indent=4)

print(f"Saved {len(all_topics)} topics to:")
print(output_path)

Saved 50 topics to:
D:\Thesis\aria2-1.37.0-win-64bit-build1\bertopic_generated_topics.json

# Visualization